# TCL File Generated by Component Editor 13.1.1
# Sun May 08 22:23:14 EDT 2016
# DO NOT MODIFY


# 
# vga_led "VGA LED Emulator" v1.3
#  2016.05.08.22:23:14
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module vga_led
# 
set_module_property DESCRIPTION ""
set_module_property NAME vga_led
set_module_property VERSION 1.3
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "VGA LED Emulator"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL VGA_LED
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file VGA_LED.sv SYSTEM_VERILOG PATH VGA_LED.sv TOP_LEVEL_FILE
add_fileset_file VGA_LED_Emulator.sv SYSTEM_VERILOG PATH VGA_LED_Emulator.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset reset Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end VGA_R export Output 8
add_interface_port conduit_end VGA_G export Output 8
add_interface_port conduit_end VGA_B export Output 8
add_interface_port conduit_end VGA_HS export Output 1
add_interface_port conduit_end VGA_CLK export Output 1
add_interface_port conduit_end VGA_BLANK_n export Output 1
add_interface_port conduit_end VGA_VS export Output 1
add_interface_port conduit_end VGA_SYNC_n export Output 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits WORDS
set_interface_property avalon_master associatedClock clock50
set_interface_property avalon_master associatedReset reset_sink
set_interface_property avalon_master bitsPerSymbol 20
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master read1 read Output 1
add_interface_port avalon_master wait_request waitrequest Input 1
add_interface_port avalon_master q_b readdata Input 20
add_interface_port avalon_master address_b address Output 16


# 
# connection point clock50
# 
add_interface clock50 clock end
set_interface_property clock50 clockRate 0
set_interface_property clock50 ENABLED true
set_interface_property clock50 EXPORT_OF ""
set_interface_property clock50 PORT_NAME_MAP ""
set_interface_property clock50 CMSIS_SVD_VARIABLES ""
set_interface_property clock50 SVD_ADDRESS_GROUP ""

add_interface_port clock50 clkmem clk Input 1


# 
# connection point ready_sig
# 
add_interface ready_sig avalon_streaming start
set_interface_property ready_sig associatedClock clock50
set_interface_property ready_sig associatedReset reset_sink
set_interface_property ready_sig dataBitsPerSymbol 1
set_interface_property ready_sig errorDescriptor ""
set_interface_property ready_sig firstSymbolInHighOrderBits true
set_interface_property ready_sig maxChannel 0
set_interface_property ready_sig readyLatency 0
set_interface_property ready_sig ENABLED true
set_interface_property ready_sig EXPORT_OF ""
set_interface_property ready_sig PORT_NAME_MAP ""
set_interface_property ready_sig CMSIS_SVD_VARIABLES ""
set_interface_property ready_sig SVD_ADDRESS_GROUP ""

add_interface_port ready_sig ready_sig data Output 1


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock50
set_interface_property avalon_streaming_sink associatedReset reset_sink
set_interface_property avalon_streaming_sink dataBitsPerSymbol 1
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink halp data Input 1

